language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:

  # install miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # create test environment with geopandas installed
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION geopandas==0.6.1
  - conda activate test-env
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
