environment:
  matrix:
    # For Python versions available on Appveyor, see 
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python37"
      MINICONDA: "C:\\Miniconda37"
      PYTHON_VERSION: 3.7

install:
  # install geopandas with conda into root python environment
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  # Useful for debugging any issues with conda
  - "conda info -a"
  # create test environment with geopandas installed
  - "conda create -q -n test-env python=%PYTHON_VERSION% geopandas"
  - "activate test-env"

  - "python setup.py develop"
  - "pip install -r %APPVEYOR_BUILD_FOLDER%\\requirements.txt"

build: off

test_script:
  - "pytest %APPVEYOR_BUILD_FOLDER%"


on_success:
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    pip install wheel &&
    python setup.py bdist_wheel &&
    pip install twine &&
    twine upload dist/* -u "%PYPI_USERNAME%" -p "%PYPI_PASSWORD%"
    )
