name: Upload Python Package

on:
  release:
    types: [published]
  workflow_run:
    workflows: [CI Tests]
    types: [completed]

permissions:
  contents: read

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
